# Generated by Django 5.0.6 on 2024-08-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='deposited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hand',
            field=models.ManyToManyField(to='blackjack_app.card'),
        ),
    ]
