# Generated by Django 5.0.6 on 2024-08-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0003_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hand',
            field=models.ManyToManyField(blank=True, to='blackjack_app.card'),
        ),
    ]
