# Generated by Django 5.0.6 on 2024-10-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0008_alter_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='blackjack_app.image'),
        ),
    ]
