# Generated by Django 5.0.6 on 2024-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0010_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='blackjack_app.image'),
        ),
    ]
